'use strict';

const {
  MonthlySummaryAggregator,
  AxlsExporter,
  DingtalkDocReport,
  autoGenerateDMinus2Trigger,
  LEAVE_TYPES,
  OT_TYPES
} = require('./src/modules/attendance/monthly_attendance_summary.js');

const {
  ATTENDANCE_ANOMALY,
  ANOMALY_NAMES
} = require('./src/modules/attendance/attendance_anomaly_engine.js');

function _seededRand(seed) {
  let s = seed;
  return function () {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

function makeTime(dateStr, hh, mm) {
  const d = new Date(dateStr);
  d.setHours(hh, mm, 0, 0);
  return d;
}

function _getAug2026Workdays() {
  const workdays = [];
  for (let d = 1; d <= 31; d++) {
    const date = new Date(2026, 7, d);
    const day = date.getDay();
    if (day >= 1 && day <= 5) {
      const mm = String(d).padStart(2, '0');
      workdays.push(`2026-08-${mm}`);
    }
  }
  return workdays;
}

const DEPT1_LIST = ['研发中心', '销售事业部', '运营支持部', '产品设计部', '行政管理部'];
const DEPT2_MAP = {
  '研发中心': ['后端组', '前端组', '测试组', '运维组'],
  '销售事业部': ['华东区', '华南区', '华北区', '渠道组'],
  '运营支持部': ['客户成功组', '数据分析组', '内容运营组'],
  '产品设计部': ['产品组', 'UI组', 'UX组'],
  '行政管理部': ['HR组', '财务组', '行政组']
};

function _generateMockData(seed = 20260828) {
  const rand = _seededRand(seed);
  const workdays = _getAug2026Workdays();

  const employees = [];
  for (let i = 1; i <= 100; i++) {
    const dept1 = DEPT1_LIST[Math.floor(rand() * DEPT1_LIST.length)];
    const dept2List = DEPT2_MAP[dept1] || ['通用组'];
    const dept2 = dept2List[Math.floor(rand() * dept2List.length)];
    employees.push({
      id: `EMP-${String(i).padStart(4, '0')}`,
      employeeId: `EMP-${String(i).padStart(4, '0')}`,
      name: `员工${String(i).padStart(3, '0')}`,
      dept1,
      dept2,
      department: dept1
    });
  }

  const punchRecords = [];
  const anomalies = [];
  const anomalyTypesArr = Object.values(ATTENDANCE_ANOMALY);
  const leaveTypeAnomalies = LEAVE_TYPES.map(lt => lt.anomalyType);

  for (let ei = 0; ei < employees.length; ei++) {
    const emp = employees[ei];
    const eid = emp.id;

    for (const wd of workdays) {
      const r = Math.random();
      const punch = {
        employeeId: eid,
        date: wd,
        checkInTime: makeTime(wd, 8, 55 + Math.floor(rand() * 20)),
        checkOutTime: makeTime(wd, 18, Math.floor(rand() * 20)),
        isMissing: false,
        source: 'mock'
      };

      const scenario = rand();
      if (scenario < 0.05) {
        punch.checkInTime = makeTime(wd, 9, 15 + Math.floor(rand() * 30));
        anomalies.push({
          anomalyId: `AT_LATE_${eid}_${wd}`,
          employeeId: eid,
          date: wd,
          type: ATTENDANCE_ANOMALY.LATE,
          typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.LATE],
          severity: 'FINE',
          deduction: scenario < 0.02 ? 20 : 0,
          ruleCodes: ['R-188', 'R-190'],
          extra: { lateMinutes: 15 + Math.floor(rand() * 30) }
        });
      } else if (scenario < 0.08) {
        punch.checkOutTime = makeTime(wd, 17, 30 - Math.floor(rand() * 20));
        anomalies.push({
          anomalyId: `AT_EARLY_${eid}_${wd}`,
          employeeId: eid,
          date: wd,
          type: ATTENDANCE_ANOMALY.EARLY_LEAVE,
          typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.EARLY_LEAVE],
          severity: 'FINE',
          deduction: 20,
          ruleCodes: ['R-192', 'R-194'],
          extra: { earlyMinutes: 15 + Math.floor(rand() * 20) }
        });
      } else if (scenario < 0.10) {
        punch.isMissing = true;
        punch.checkInTime = null;
        punch.checkOutTime = null;
        anomalies.push({
          anomalyId: `AT_MISS_${eid}_${wd}`,
          employeeId: eid,
          date: wd,
          type: ATTENDANCE_ANOMALY.MISSING_PUNCH,
          typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.MISSING_PUNCH],
          severity: 'FINE',
          deduction: 50,
          ruleCodes: ['R-196'],
          extra: { missingPunchCount: 1 }
        });
      } else if (scenario < 0.11) {
        punch.isMissing = true;
        punch.checkInTime = null;
        punch.checkOutTime = null;
        anomalies.push({
          anomalyId: `AT_ABS_${eid}_${wd}`,
          employeeId: eid,
          date: wd,
          type: ATTENDANCE_ANOMALY.ABSENT,
          typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.ABSENT],
          severity: 'DEDUCT',
          deduction: 0,
          absentDays: 1,
          ruleCodes: ['R-197'],
          extra: { absentDays: 1 }
        });
      } else if (scenario < 0.15) {
        punch.checkOutTime = makeTime(wd, 20, 30 + Math.floor(rand() * 60));
        const otHrs = 2 + Math.floor(rand() * 4);
        anomalies.push({
          anomalyId: `AT_OTWD_${eid}_${wd}`,
          employeeId: eid,
          date: wd,
          type: ATTENDANCE_ANOMALY.OT_WORKDAY,
          typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.OT_WORKDAY],
          severity: 'DEDUCT',
          deduction: 0,
          otHours: otHrs,
          ruleCodes: ['R-198'],
          extra: { otHours: otHrs, rate: 1.5 }
        });
      } else if (scenario < 0.18) {
        const leaveType = leaveTypeAnomalies[Math.floor(rand() * leaveTypeAnomalies.length)];
        punch.leaveApprovalNo = `APR-LV-${eid}-${wd}`;
        punch.checkInTime = null;
        punch.checkOutTime = null;
        anomalies.push({
          anomalyId: `AT_LV_${eid}_${wd}_${leaveType}`,
          employeeId: eid,
          date: wd,
          type: leaveType,
          typeName: ANOMALY_NAMES[leaveType],
          severity: 'WARNING',
          deduction: 0,
          leaveType,
          ruleCodes: ['R-201'],
          approvalNo: punch.leaveApprovalNo
        });
      } else if (scenario < 0.19) {
        punch.fieldWorkFlag = true;
        punch.businessTripNo = null;
        anomalies.push({
          anomalyId: `AT_UFW_${eid}_${wd}`,
          employeeId: eid,
          date: wd,
          type: ATTENDANCE_ANOMALY.UNAPPROVED_FIELDWORK,
          typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.UNAPPROVED_FIELDWORK],
          severity: 'FINE',
          deduction: 0,
          ruleCodes: ['R-202'],
          extra: { fieldWorkFlag: true }
        });
      }
      punchRecords.push(punch);
    }

    const extraOtDays = Math.floor(rand() * 2);
    for (let k = 0; k < extraOtDays; k++) {
      const weekendDate = `2026-08-${String(1 + k * 7).padStart(2, '0')}`;
      const otHrs = 4 + Math.floor(rand() * 5);
      anomalies.push({
        anomalyId: `AT_OTWE_${eid}_WK${k}`,
        employeeId: eid,
        date: weekendDate,
        type: ATTENDANCE_ANOMALY.OT_WEEKEND,
        typeName: ANOMALY_NAMES[ATTENDANCE_ANOMALY.OT_WEEKEND],
        severity: 'DEDUCT',
        deduction: 0,
        otHours: otHrs,
        ruleCodes: ['R-199'],
        extra: { otHours: otHrs, rate: 2.0 }
      });
    }
  }

  return {
    year: 2026,
    month: 8,
    employees,
    punchRecords,
    anomalies,
    workdays
  };
}

function manualAggregate({ year, month, employees, punchRecords, anomalies }) {
  const { workdays: monthWorkdays } = (function () {
    let workdays = 0;
    const m = month - 1;
    const last = new Date(year, m + 1, 0);
    const total = last.getDate();
    for (let d = 1; d <= total; d++) {
      const dw = new Date(year, m, d).getDay();
      if (dw >= 1 && dw <= 5) workdays++;
    }
    return { totalDays: total, workdays };
  })();

  const empMap = new Map();
  for (const e of employees) empMap.set(String(e.id || e.employeeId), e);

  const anomaliesByEmp = new Map();
  for (const a of anomalies) {
    const k = String(a.employeeId);
    if (!anomaliesByEmp.has(k)) anomaliesByEmp.set(k, []);
    anomaliesByEmp.get(k).push(a);
  }

  const empResults = [];
  for (const e of employees) {
    const eid = String(e.id || e.employeeId);
    const list = anomaliesByEmp.get(eid) || [];
    let lateCount = 0, earlyLeaveCount = 0, missingCount = 0;
    let absentDays = 0, totalFine = 0, otHours = 0;
    const eachLeaveTypeDays = {};
    for (const lt of LEAVE_TYPES) eachLeaveTypeDays[lt.key] = 0;

    for (const a of list) {
      const t = a.type;
      if (t === ATTENDANCE_ANOMALY.LATE) lateCount++;
      else if (t === ATTENDANCE_ANOMALY.EARLY_LEAVE) earlyLeaveCount++;
      else if (t === ATTENDANCE_ANOMALY.MISSING_PUNCH) missingCount++;
      else if (t === ATTENDANCE_ANOMALY.ABSENT) absentDays += Number(a.absentDays || (a.extra && a.extra.absentDays) || 1);

      if (OT_TYPES.includes(t)) {
        otHours += Number(a.otHours || (a.extra && a.extra.otHours) || 0);
      }

      for (const lt of LEAVE_TYPES) {
        if (t === lt.anomalyType) eachLeaveTypeDays[lt.key] += 1;
      }
      totalFine += Number(a.deduction || 0);
    }

    const leaveTotal = Object.values(eachLeaveTypeDays).reduce((s, v) => s + v, 0);
    const actualAttendanceDays = Math.max(0, monthWorkdays - absentDays - leaveTotal);

    empResults.push({
      employeeId: eid,
      name: e.name || '',
      dept1: e.dept1 || e.department || '',
      dept2: e.dept2 || '',
      lateCount,
      earlyLeaveCount,
      missingCount,
      absentDays,
      totalFine,
      otHours: Number(otHours.toFixed(1)),
      eachLeaveTypeDays,
      actualAttendanceDays
    });
  }

  const deptMap = new Map();
  for (const es of empResults) {
    const k = `${es.dept1 || '未分配'}||${es.dept2 || ''}`;
    if (!deptMap.has(k)) {
      deptMap.set(k, {
        dept1: es.dept1 || '未分配',
        dept2: es.dept2 || '',
        totalEmployees: 0,
        lateCount: 0,
        earlyLeaveCount: 0,
        missingCount: 0,
        absentDays: 0,
        otTotalHours: 0,
        leaveDays: (function () { const o = {}; for (const lt of LEAVE_TYPES) o[lt.key] = 0; return o; })()
      });
    }
    const d = deptMap.get(k);
    d.totalEmployees++;
    d.lateCount += es.lateCount;
    d.earlyLeaveCount += es.earlyLeaveCount;
    d.missingCount += es.missingCount;
    d.absentDays += es.absentDays;
    d.otTotalHours += es.otHours;
    for (const lt of LEAVE_TYPES) {
      d.leaveDays[lt.key] += es.eachLeaveTypeDays[lt.key];
    }
  }

  const deptList = Array.from(deptMap.values());
  deptList.forEach(d => d.otTotalHours = Number(d.otTotalHours.toFixed(1)));

  return {
    employeeDimension: empResults,
    departmentDimension: deptList,
    monthWorkdays
  };
}

async function test_TR281() {
  console.log('\n============= TR-2.8.1: 100名员工模拟数据+人工汇总对比测试 =============');

  const mock = _generateMockData(20260828);
  console.log(`[TR-2.8.1] 构造模拟数据：`);
  console.log(`  - 员工数：${mock.employees.length} 人（期望=100）`);
  console.log(`  - 打卡记录：${mock.punchRecords.length} 条`);
  console.log(`  - 异常记录：${mock.anomalies.length} 条`);
  console.log(`  - 报告月份：${mock.year}年${mock.month}月，工作日：${mock.workdays.length}天`);

  const aggregator = new MonthlySummaryAggregator();
  const summary = aggregator.calcMonthlySummary(mock);

  console.log(`\n[TR-2.8.1] calcMonthlySummary 执行完成：`);
  console.log(`  - 部门维度块数：${summary.departmentDimension.length}`);
  console.log(`  - 员工维度块数：${summary.employeeDimension.length}`);
  console.log(`  - 16类异常排名长度：${summary.anomalyTypeDimension.anomalyTypeRanking.length}`);
  console.log(`  - 加班TOP10长度：${summary.anomalyTypeDimension.otTop10.length}`);
  console.log(`  - 异常TOP10长度：${summary.anomalyTypeDimension.anomalyTop10.length}`);

  const manual = manualAggregate(mock);
  console.log(`\n[TR-2.8.1] 人工汇总函数执行完成：`);
  console.log(`  - 部门维度块数：${manual.departmentDimension.length}`);
  console.log(`  - 员工维度块数：${manual.employeeDimension.length}`);

  const empCalcMap = new Map();
  for (const e of summary.employeeDimension) empCalcMap.set(e.employeeId, e);

  let empExactMatch = 0;
  const mismatchDetails = [];
  for (const me of manual.employeeDimension) {
    const ce = empCalcMap.get(me.employeeId);
    if (!ce) continue;

    const ok = (
      me.lateCount === ce.lateCount &&
      me.earlyLeaveCount === ce.earlyLeaveCount &&
      me.missingCount === ce.missingCount &&
      Math.abs(me.absentDays - ce.absentDays) < 0.001 &&
      Math.abs(me.totalFine - ce.totalFine) < 0.01 &&
      Math.abs(me.otHours - ce.otHours) < 0.05 &&
      Math.abs(me.actualAttendanceDays - ce.actualAttendanceDays) < 0.001 &&
      LEAVE_TYPES.every(lt => me.eachLeaveTypeDays[lt.key] === ce.eachLeaveTypeDays[lt.key])
    );

    if (ok) empExactMatch++;
    else {
      mismatchDetails.push({
        employeeId: me.employeeId,
        manual: { late: me.lateCount, early: me.earlyLeaveCount, miss: me.missingCount, absent: me.absentDays, fine: me.totalFine, ot: me.otHours },
        calc: { late: ce.lateCount, early: ce.earlyLeaveCount, miss: ce.missingCount, absent: ce.absentDays, fine: ce.totalFine, ot: ce.otHours }
      });
    }
  }

  const empDiff = 100 - empExactMatch;
  const empDiffOk = empDiff <= 1;
  console.log(`\n[TR-2.8.1] 员工维度对比（共100人）：`);
  console.log(`  - 完全一致：${empExactMatch}/100 人`);
  console.log(`  - 差异人数：${empDiff} 人（阈值≤1）：${empDiffOk ? '✅ 通过' : '❌ 未通过'}`);
  if (mismatchDetails.length > 0 && mismatchDetails.length <= 5) {
    for (const md of mismatchDetails.slice(0, 3)) {
      console.log(`    * 差异员工 ${md.employeeId}: manual vs calc`);
      console.log(`      late=${md.manual.late}/${md.calc.late}, early=${md.manual.early}/${md.calc.early}, miss=${md.manual.miss}/${md.calc.miss}`);
      console.log(`      absent=${md.manual.absent}/${md.calc.absent}, fine=${md.manual.fine}/${md.calc.fine}, ot=${md.manual.ot}/${md.calc.ot}`);
    }
  }

  const deptCalcMap = new Map();
  for (const d of summary.departmentDimension) {
    deptCalcMap.set(`${d.dept1}||${d.dept2}`, d);
  }

  let deptMismatchCount = 0;
  const deptTotalCounts = manual.departmentDimension.length || 1;
  for (const md of manual.departmentDimension) {
    const k = `${md.dept1}||${md.dept2}`;
    const cd = deptCalcMap.get(k);
    if (!cd) { deptMismatchCount++; continue; }

    const diffs = [
      ['lateCount', md.lateCount, cd.lateCount],
      ['earlyLeaveCount', md.earlyLeaveCount, cd.earlyLeaveCount],
      ['missingCount', md.missingCount, cd.missingCount],
      ['absentDays', md.absentDays, cd.absentDays],
      ['otTotalHours', md.otTotalHours, cd.otTotalHours],
      ['totalEmployees', md.totalEmployees, cd.totalEmployees]
    ];
    for (const [name, mv, cv] of diffs) {
      const denom = Math.max(1, Math.max(mv, cv));
      const ratio = Math.abs(mv - cv) / denom;
      if (ratio > 0.005) {
        deptMismatchCount++;
      }
    }
    for (const lt of LEAVE_TYPES) {
      const mv = md.leaveDays[lt.key];
      const cv = cd.leaveDays[lt.key];
      const denom = Math.max(1, Math.max(mv, cv));
      const ratio = Math.abs(mv - cv) / denom;
      if (ratio > 0.005) deptMismatchCount++;
    }
  }

  const totalDeptComparisons = deptTotalCounts * (6 + LEAVE_TYPES.length);
  const deptDiffRatio = totalDeptComparisons > 0 ? deptMismatchCount / totalDeptComparisons : 0;
  const deptDiffOk = deptDiffRatio <= 0.005;

  console.log(`\n[TR-2.8.1] 部门维度counts差额对比：`);
  console.log(`  - 部门汇总块总数：${deptTotalCounts}`);
  console.log(`  - 总比较项数：${totalDeptComparisons}`);
  console.log(`  - 超0.5%差额的项数：${deptMismatchCount}`);
  console.log(`  - 部门差额比例：${(deptDiffRatio * 100).toFixed(3)}%（阈值≤0.5%）：${deptDiffOk ? '✅ 通过' : '❌ 未通过'}`);

  const pass = empDiffOk && deptDiffOk;
  console.log(`\n[TR-2.8.1] 结果：${pass ? '✅ PASS (员工差异≤1人, 部门差额≤0.5%)' : '❌ FAIL'}`);

  const top3 = summary.anomalyTypeDimension.otTop10.slice(0, 3);
  console.log(`\n  [加班TOP3样例]:`);
  for (const t of top3) {
    console.log(`    第${t.rank}名 ${t.name}(${t.employeeId}) dept=${t.dept1} ot=${t.otHours}h`);
  }
  const top3a = summary.anomalyTypeDimension.anomalyTop10.slice(0, 3);
  console.log(`  [异常TOP3样例]:`);
  for (const t of top3a) {
    console.log(`    第${t.rank}名 ${t.name}(${t.employeeId}) dept=${t.dept1} count=${t.count}`);
  }
  const top3t = summary.anomalyTypeDimension.anomalyTypeRanking.slice(0, 5);
  console.log(`  [16类异常排名TOP5样例]:`);
  for (const t of top3t) {
    console.log(`    ${t.typeName}(${t.type}) count=${t.count}`);
  }

  return { pass, summary };
}

async function test_TR282() {
  console.log('\n============= TR-2.8.2: Axls在线表格结构+Doc报告章节验证 =============');

  const mock = _generateMockData(20260828 + 1);
  const aggregator = new MonthlySummaryAggregator();
  const summary = aggregator.calcMonthlySummary(mock);

  const actualDept1Set = new Set((mock.employees || []).map(e => e.dept1 || e.department || '未分配部门'));
  const actualDept1Count = actualDept1Set.size;
  console.log(`[TR-2.8.2] 输入实际不同dept1一级部门数：${actualDept1Count}（期望≥3）`);
  for (const d of actualDept1Set) console.log(`  - ${d}`);

  const axlsExporter = new AxlsExporter();
  const axls = axlsExporter.buildAxlsStructure(summary);
  console.log(`\n[TR-2.8.2] buildAxlsStructure 输出：`);
  console.log(`  - workbookTitle: ${axls.workbookTitle}`);
  console.log(`  - totalSheets: ${axls.totalSheets}`);
  for (const s of axls.sheets) console.log(`    * Sheet名: ${s.sheetName} / 员工行数: ${s.dataRows.length} / 合计行公式数: ${Object.keys(s.sumFormulas).length}`);

  const sheetCountOk = axls.totalSheets === actualDept1Count && actualDept1Count >= 3;
  console.log(`\n  校验① 部门sheet数量=${actualDept1Count}(实际dept1数)且≥3: ${sheetCountOk ? '✅ 通过' : '❌ 未通过'} (实际sheet数=${axls.totalSheets})`);

  const sumFormulaRegex = /=SUM\(([A-Z]{1,3})(\d+)\:([A-Z]{1,3})(\d+)\)/;
  let allSheetsSumFormulasOk = true;
  let sheetFailReason = '';
  for (const s of axls.sheets) {
    const formulasToCheck = [
      s.sumFormulas.actualAttendanceSum,
      s.sumFormulas.lateCountSum,
      s.sumFormulas.earlyLeaveCountSum,
      s.sumFormulas.missingCountSum,
      s.sumFormulas.totalFineSum
    ];
    const matches = formulasToCheck.filter(f => sumFormulaRegex.test(f || ''));
    if (matches.length < 5) {
      allSheetsSumFormulasOk = false;
      sheetFailReason = `Sheet(${s.sheetName})仅${matches.length}/5个SUM公式通过`;
      console.log(`    Sheet[${s.sheetName}] SUM公式匹配结果：${matches.length}/5`);
      formulasToCheck.forEach((f, i) => {
        console.log(`      公式#${i + 1}: "${f || ''}" -> ${sumFormulaRegex.test(f || '') ? '匹配✅' : '不匹配❌'}`);
      });
      break;
    }
  }
  console.log(`  校验② 每个部门Sheet末尾合计行5个=SUM()公式正则通过: ${allSheetsSumFormulasOk ? '✅ 通过' : '❌ 未通过 - ' + sheetFailReason}`);

  const docBuilder = new DingtalkDocReport();
  const doc = docBuilder.buildDocReport(summary);
  console.log(`\n[TR-2.8.2] buildDocReport 输出：`);
  console.log(`  - docTitle: ${doc.docTitle}`);
  console.log(`  - sections数: ${doc.sections.length}`);
  console.log(`  - 富文本大纲章节:`);
  for (const o of doc.richTextOutline) console.log(`    * ${o}`);

  const hasAnomalyTop10Chapter = (function () {
    const t = '异常TOP10';
    const hit1 = doc.richTextOutline.some(s => String(s).includes(t));
    const hit2 = doc.sections.some(s => (s.title && String(s.title).includes('异常TOP10')) || (s.type === 'section' && s.rankingTable));
    const hit3 = doc.hasAnomalyTop10 === true;
    return hit1 || hit2 || hit3;
  })();

  const hasOtTop10Chapter = (function () {
    const t = '加班TOP10';
    const hit1 = doc.richTextOutline.some(s => String(s).includes(t));
    const hit2 = doc.sections.some(s => (s.title && String(s.title).includes('加班TOP10')));
    const hit3 = doc.hasOtTop10 === true;
    return hit1 || hit2 || hit3;
  })();

  const hasLeaveChapter = (function () {
    const keywords = ['假期消耗', '年假', '病假', '事假'];
    const hit1 = doc.richTextOutline.some(s => keywords.some(k => String(s).includes(k)));
    const hit2 = doc.sections.some(s => {
      const t = String(s.title || '');
      return keywords.some(k => t.includes(k)) || s.consumptionTable;
    });
    const hit3 = doc.hasLeaveConsumption === true;
    return hit1 || hit2 || hit3;
  })();

  console.log(`\n  校验③ Doc报告包含异常TOP10章节: ${hasAnomalyTop10Chapter ? '✅ 通过' : '❌ 未通过'}`);
  console.log(`  校验④ Doc报告包含加班TOP10章节: ${hasOtTop10Chapter ? '✅ 通过' : '❌ 未通过'}`);
  console.log(`  校验⑤ Doc报告包含假期消耗章节: ${hasLeaveChapter ? '✅ 通过' : '❌ 未通过'}`);

  const pass = sheetCountOk && allSheetsSumFormulasOk && hasAnomalyTop10Chapter && hasOtTop10Chapter && hasLeaveChapter;

  const trigger = autoGenerateDMinus2Trigger({ now: new Date(2026, 7, 20, 9, 0, 0) });
  console.log(`\n  [D-2 10:00调度样例(当前=2026/8/20)]:`);
  console.log(`    triggerLabel: ${trigger.triggerLabel}`);
  console.log(`    cronExpression: ${trigger.cronExpression}`);
  console.log(`    targetReport: ${trigger.targetReport.label}`);
  console.log(`    millisecondsUntilTrigger: ${trigger.millisecondsUntilTrigger}`);

  console.log(`\n[TR-2.8.2] 结果：${pass ? '✅ PASS (全部5项校验通过)' : '❌ FAIL'}`);
  return { pass, axls, doc };
}

(async function runAll() {
  console.log('========================================================================');
  console.log('智慧化人资平台 Task2.8 月度考勤汇总与确认单自动生成 测试套件');
  console.log('========================================================================');
  console.log('\n【输出文件路径】:');
  console.log('  核心模块文件: src/modules/attendance/monthly_attendance_summary.js');
  console.log('  主要导出:');
  console.log('    ① MonthlySummaryAggregator.calcMonthlySummary({year, month, employees, punchRecords, anomalies})');
  console.log('       → 输出三维度: departmentDimension / employeeDimension / anomalyTypeDimension');
  console.log('    ② AxlsExporter.buildAxlsStructure(summary)');
  console.log('       → 钉钉在线表格结构: sheets[].totalRow含=SUM()公式');
  console.log('    ③ DingtalkDocReport.buildDocReport(summary)');
  console.log('       → 富文本报告含标题/摘要/异常TOP10/加班TOP10/假期消耗/16类排名共6部分');
  console.log('    ④ autoGenerateDMinus2Trigger(options)');
  console.log('       → 次月D-2日10:00自动生成, 返回{cronExpression, triggerTime, targetReport}');
  console.log('  测试文件: test_task28.js (本文件)');

  const r1 = await test_TR281();
  const r2 = await test_TR282();

  const p1 = r1.pass;
  const p2 = r2.pass;

  console.log('\n========================================================================');
  console.log('测试总结:');
  console.log(`  TR-2.8.1 (100员工模拟+人工汇总对比: 员工差≤1人, 部门差≤0.5%): ${p1 ? '✅ PASS' : '❌ FAIL'}`);
  console.log(`  TR-2.8.2 (Axls结构+Doc报告章节共5项校验全部通过):           ${p2 ? '✅ PASS' : '❌ FAIL'}`);
  console.log(`  总体:   ${(p1 && p2) ? '🎉 全部通过' : '⚠️ 存在失败用例'}`);
  console.log('========================================================================');
})();
